# Generated by Django 3.1 on 2020-11-01 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import rrbnstaff.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requisition_no', models.CharField(blank=True, default=rrbnstaff.models.increment_requisition_no, max_length=500, null=True)),
                ('quantity_requested', models.IntegerField()),
                ('department', models.CharField(max_length=200)),
                ('requisition_date', models.DateTimeField(auto_now_add=True)),
                ('requisition_status', models.IntegerField(default=1)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='store.item')),
                ('requesting_staff', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
