# Generated by Django 3.1 on 2020-11-18 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import rrbnstaff.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requisition_no', models.CharField(blank=True, default=rrbnstaff.models.increment_requisition_no, max_length=500, null=True)),
                ('quantity_requested', models.IntegerField()),
                ('department', models.CharField(max_length=200)),
                ('requisition_date', models.DateTimeField(auto_now_add=True)),
                ('requisition_status', models.IntegerField(default=1)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='store.item')),
                ('requesting_staff', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requisition_date'],
                'unique_together': {('requisition_no', 'requesting_staff')},
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_no', models.CharField(blank=True, default=rrbnstaff.models.increment_request_no, max_length=500, null=True)),
                ('department', models.CharField(max_length=200)),
                ('request_reason', models.TextField(blank=True, null=True)),
                ('destination', models.CharField(max_length=200)),
                ('request_duration', models.CharField(choices=[('1 day', '1 day'), ('2 days', '2 days'), ('3 days', '3 days'), ('4 days', '4 days'), ('1 week', '1 week'), ('2 weeks', '2 weeks')], default='1 day', max_length=120)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('trip_date', models.DateTimeField(auto_now_add=True)),
                ('request_status', models.IntegerField(default=1)),
                ('requesting_staff', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fleet.vehicle')),
            ],
            options={
                'ordering': ['-request_date'],
                'unique_together': {('request_no', 'requesting_staff')},
            },
        ),
    ]
