# Generated by Django 3.1 on 2020-11-05 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrbnstaff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
