# Generated by Django 3.1 on 2020-11-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrbnstaff', '0002_auto_20201105_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='trip_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
