# Generated by Django 3.1 on 2020-12-14 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrbnstaff', '0002_auto_20201213_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_reason',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
