# Generated by Django 3.1 on 2020-12-19 18:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rrbnstaff', '0004_auto_20201215_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='trip_date',
            new_name='projected_start_date',
        ),
        migrations.AddField(
            model_name='request',
            name='projected_end_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
