# Generated by Django 3.1 on 2020-12-21 06:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rrbnstaff', '0006_auto_20201219_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='projected_end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='request',
            name='projected_start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
