# Generated by Django 3.1 on 2020-12-21 23:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rrbnstaff', '0008_auto_20201221_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='projected_end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='request',
            name='projected_start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
