# Generated by Django 3.1 on 2022-01-27 21:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import store.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('entry_date', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('item_description', models.TextField()),
                ('stock_code', models.CharField(max_length=200, unique=True)),
                ('unit', models.CharField(choices=[('Ream', 'Ream'), ('PC', 'PC'), ('Pkt', 'Pkt'), ('Booklet', 'Booklet'), ('Roll', 'Roll'), ('Bottle', 'Bottle'), ('Yard', 'Yard'), ('Sheet', 'Sheet'), ('Pad', 'Pad'), ('Tab', 'Tab'), ('Tin', 'Tin'), ('Pack', 'Pack')], max_length=100)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('re_order_no', models.IntegerField()),
                ('item_image', models.ImageField(blank=True, upload_to='%Y/%m/%d/')),
                ('entry_date', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('below_re_order_date', models.DateField(blank=True, default=datetime.date.today)),
                ('unavailable_date', models.DateField(blank=True, default=datetime.date.today)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='default_category', to='store.category')),
                ('entered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-entry_date'],
            },
        ),
        migrations.CreateModel(
            name='RequisitionCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisition_date', models.DateField(auto_now_add=True)),
                ('requisition_status', models.IntegerField(default=1)),
                ('requisition_no', models.CharField(blank=True, default=store.models.increment_requisition_no, max_length=500, null=True)),
                ('employee', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='requisition_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Restock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restock_no', models.CharField(blank=True, default=store.models.increment_restock_no, max_length=500, null=True, unique=True)),
                ('item_name', models.CharField(max_length=200)),
                ('item_description', models.TextField(blank=True, null=True)),
                ('stock_code', models.CharField(max_length=200)),
                ('unit', models.CharField(choices=[('Ream', 'Ream'), ('PC', 'PC'), ('Pkt', 'Pkt'), ('Booklet', 'Booklet'), ('Roll', 'Roll'), ('Bottle', 'Bottle'), ('Yard', 'Yard'), ('Sheet', 'Sheet'), ('Pad', 'Pad'), ('Tab', 'Tab'), ('Tin', 'Tin'), ('Pack', 'Pack')], max_length=100)),
                ('quantity_ordered', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('quantity_received', models.IntegerField()),
                ('received_on', models.DateField(blank=True, default=datetime.date.today)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='item_category', to='store.category')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='received_by', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='store.vendor')),
            ],
            options={
                'ordering': ['-received_on'],
            },
        ),
        migrations.CreateModel(
            name='RequisitionCartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.item')),
                ('requisition_cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.requisitioncart')),
            ],
        ),
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisition_reason', models.TextField(blank=True)),
                ('requisition_creation_date', models.DateField(auto_now_add=True)),
                ('requisition_status', models.IntegerField(default=1)),
                ('department', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='requesting_department', to='hr.department')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.employee')),
                ('hod', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='approved_by', to='hr.employee')),
                ('requisition_cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.requisitioncart')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='store.vendor'),
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_issued', models.IntegerField(blank=True, default=0, null=True)),
                ('issue_date', models.DateField(blank=True, default=datetime.date.today)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='issuing_staff', to=settings.AUTH_USER_MODEL)),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.requisition')),
            ],
        ),
    ]
