# Generated by Django 3.1 on 2020-12-15 16:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='item',
            new_name='item_name',
        ),
        migrations.AlterUniqueTogether(
            name='issue',
            unique_together={('requisition_no', 'requesting_staff'), ('requisition_no', 'item_name')},
        ),
    ]
