# Generated by Django 3.1 on 2020-12-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20201215_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='item_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
