# Generated by Django 3.1 on 2022-04-03 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20220403_0908'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisitionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('quantity_issued', models.IntegerField(blank=True, default=0, null=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.item')),
                ('requisition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.requisition')),
            ],
        ),
    ]
