# Generated by Django 3.1 on 2022-04-05 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_auto_20220403_0755'),
        ('store', '0009_auto_20220403_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='department',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='hr.department'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requisition',
            name='employee',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='requested_by', to='hr.employee'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requisition',
            name='hod',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='approved_by', to='hr.employee'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requisition',
            name='requisition_cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.requisitioncart'),
            preserve_default=False,
        ),
    ]
