# Generated by Django 3.1 on 2022-04-06 12:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0010_auto_20220405_1244'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Issue',
            new_name='IssueRequisition',
        ),
    ]
