# Generated by Django 3.1 on 2022-04-07 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20220406_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuerequisition',
            name='employee',
        ),
    ]
