# Generated by Django 3.1 on 2022-04-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_remove_issuerequisition_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitioncartitem',
            name='quantity_issued',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
