# Generated by Django 3.1 on 2022-04-07 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_requisitioncartitem_quantity_issued'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuerequisition',
            name='quantity_issued',
        ),
    ]
