# Generated by Django 3.1 on 2022-04-22 16:37

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_remove_issuerequisition_quantity_issued'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='stock_code',
            field=models.CharField(blank=True, default=store.models.increment_stock_code, max_length=500, null=True),
        ),
    ]
