# Generated by Django 3.1 on 2022-04-22 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20220422_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='stock_code',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
