# Generated by Django 3.1 on 2022-04-23 02:45

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20220422_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_short',
            field=models.CharField(default=1, max_length=120, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='stock_code',
            field=models.CharField(blank=True, default=store.models.increment_stock_code, max_length=500, null=True),
        ),
    ]
