# Generated by Django 3.1 on 2022-04-23 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_auto_20220423_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='stock_code',
            field=models.CharField(blank=True, default=1, max_length=500, null=True),
        ),
    ]
