# Generated by Django 3.1 on 2022-04-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_auto_20220425_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='stock_code',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
