from django.urls import path
from . import views
from .views import (
    DashboardTemplateView,
    RequestItem,
    ItemCountView,
    RequisitionCheckout,
    CreateRequisition,
    RequisitionUpdateView,
    RequisitionDeleteView,
    ItemCategoyListView,
    ItemsListView,
    ItemListView,
    ItemCreateView,
    ItemDetailView,
    ItemUpdateView,
    ItemDeleteView,
    CategoryCreateView,
    CategoryDetailView,
    CategoryUpdateView,
    CategoryDeleteView,
    VendorListView,
    VendorCreateView,
    VendorDetailView,
    VendorUpdateView,
    VendorDeleteView,
    RequisitionListView,
    RequisitionDetailsView,
    IssueRequisition,
    IssueRequisitionUpdate,
    IssuedRequisitions,
    IssuedRequisitionsDetailView,
    RestockItem,
    ReceivedItemsList,
    ItemRestockDetails,

)


app_name = 'store'

urlpatterns = [
	path('dashboard', DashboardTemplateView.as_view(), name='store_dashboard'),
    path('retrieve_item', views.retrieve_item, name='retrieve_item'),
    path('find_item/', views.find_item, name='find_item'),
    path('request_item/', RequestItem.as_view(), name='create_item_requisition'),
    path('request_item/count/', ItemCountView.as_view(), name='requsition_item_count'),
    path('requisition_checkout/', RequisitionCheckout.as_view(), name='requisition_checkout'),
    path('<int:pk>/requisition_update/', RequisitionUpdateView.as_view(), name='requisition_update'),
    path('<int:id>/requisition_delete/', RequisitionDeleteView.as_view(), name='requisition_delete'),
    path('<int:id>/create_requisition/', CreateRequisition.as_view(), name='create_requisition'),
    path('<int:id>/requisition_details/', RequisitionDetailsView.as_view(), name='requisition_details'),
    path('restock/', views.restock, name='restock'),
    path('<int:id>/restock/', RestockItem.as_view(), name='restock_item'),
    path('restock_list/', ReceivedItemsList.as_view(), name='restock_list'), 
    path('<int:pk>/restock_details/', ItemRestockDetails.as_view(), name='restock_details'),
	path('category_list/', ItemCategoyListView.as_view(), name='category_list'), 
	path('items_list/', ItemsListView.as_view(), name='items_list'),
	path('vendor_list/', VendorListView.as_view(), name='vendor_list'),
    path('requisition_list/', RequisitionListView.as_view(), name='requisition_list'), 
    path('issue_list/', IssuedRequisitions.as_view(), name='issue_list'), 
	path('create_item/', ItemCreateView.as_view(), name='create_item'),
	path('create_vendor/', VendorCreateView.as_view(), name='create_vendor'),
	path('create_category/', CategoryCreateView.as_view(), name='create_category'),
	path('<int:pk>/item_detail/', ItemDetailView.as_view(), name='item_detail'),
    path('item_list/', ItemListView.as_view(), name='item_list'),
    path('<int:pk>/issue_details/', IssuedRequisitionsDetailView.as_view(), name='issue_details'),
    path('<int:id>/vendor_detail/', VendorDetailView.as_view(), name='vendor_detail'),
	path('<int:id>/category_detail/', CategoryDetailView.as_view(), name='category_detail'),
	path('<int:pk>/item_update/', ItemUpdateView.as_view(), name='item_update'),
	path('<int:pk>/category_update/', CategoryUpdateView.as_view(), name='category_update'),
	path('<int:pk>/vendor_update/', VendorUpdateView.as_view(), name='vendor_update'),
	path('<int:id>/item_delete/', ItemDeleteView.as_view(), name='item_delete'),
	path('<int:id>/category_delete/', CategoryDeleteView.as_view(), name='category_delete'),
	path('<int:id>/vendor_delete/', VendorDeleteView.as_view(), name='vendor_delete'),
    path('<int:id>/requisition', IssueRequisition.as_view(), name='issue_requisition'),
    path('<int:id>/update_requisition/', IssueRequisitionUpdate.as_view(), name='update_requisition'),

    
    ]