# Generated by Django 3.1 on 2020-11-01 14:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('line_manager', models.CharField(max_length=100)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('dob', models.DateTimeField(auto_now_add=True)),
                ('gender', models.CharField(max_length=200)),
                ('marital_status', models.CharField(max_length=100)),
                ('next_of_kin', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('zone', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('national_id', models.CharField(max_length=100)),
                ('employee_id', models.CharField(max_length=100)),
                ('contact_address', models.TextField(blank=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('state_of_origin', models.CharField(max_length=100)),
                ('local_government_area', models.CharField(max_length=100)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('pension_date', models.DateTimeField(auto_now_add=True)),
                ('qualiification', models.CharField(max_length=100)),
                ('languages', models.CharField(max_length=100)),
                ('professional_organizations', models.CharField(max_length=100)),
                ('blood_group', models.CharField(max_length=100)),
                ('drivers_license', models.ImageField(blank=True, upload_to='%Y/%m/%d/')),
                ('digital_passport', models.ImageField(blank=True, upload_to='%Y/%m/%d/')),
                ('special_interests', models.TextField(blank=True)),
                ('hobbies', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Learning',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('training_name', models.CharField(max_length=200)),
                ('training_venue', models.CharField(max_length=200)),
                ('training_vendor', models.CharField(max_length=200)),
                ('training_objectives', models.TextField(blank=True)),
                ('staff_names', models.TextField(blank=True)),
                ('unit', models.CharField(max_length=200)),
                ('grade', models.CharField(max_length=200)),
                ('training_cost', models.DecimalField(decimal_places=2, max_digits=50)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=200)),
                ('reason', models.CharField(max_length=200)),
                ('leave_type', models.CharField(max_length=200)),
                ('leave_compliance', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_performance_review', models.DateTimeField(auto_now_add=True)),
                ('performance_review_date', models.DateTimeField(auto_now_add=True)),
                ('next_performance_review', models.DateTimeField(auto_now_add=True)),
                ('performance_notes', models.TextField(blank=True)),
                ('rate', models.IntegerField()),
                ('reviewer', models.CharField(max_length=100)),
                ('comments', models.TextField(blank=True)),
            ],
        ),
    ]
