# Generated by Django 3.1 on 2021-02-08 23:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr', '0001_initial_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='staff_name',
            field=models.ManyToManyField(related_name='scheduled_staff', to=settings.AUTH_USER_MODEL),
        ),
    ]
