# Generated by Django 3.1 on 2021-01-27 17:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_auto_20210127_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
