# Generated by Django 3.1 on 2021-02-12 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr', '0002_auto_20210208_2308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='performance',
            options={'ordering': ['-documented_on']},
        ),
        migrations.AlterField(
            model_name='employee',
            name='staff_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='performance',
            unique_together={('schedule_no', 'staff_name')},
        ),
    ]
