# Generated by Django 3.1 on 2021-01-27 22:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_title_date_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pay_grade_name', models.CharField(max_length=200)),
                ('paygrade_description', models.TextField(blank=True, null=True)),
                ('pay_grade_code', models.CharField(max_length=200, unique=True)),
            ],
        ),
    ]
