# Generated by Django 3.1 on 2021-01-28 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_auto_20210128_1747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='qualiification',
            new_name='qualification',
        ),
    ]
