# Generated by Django 3.1 on 2022-05-11 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('phone_no', models.CharField(blank=True, max_length=100)),
                ('zone', models.CharField(blank=True, choices=[('HQ', 'HQ'), ('Lagos Zonal Office ', 'Lagos Zonal Office'), ('Lagos CERT-RADMIRS', 'Lagos CERT-RADMIRS'), ('Asaba', 'Asaba'), ('Enugu', 'Enugu'), ('Port Harcourt', 'Port Harcourt'), ('Kano', 'Kano'), ('Sokoto', 'Sokoto'), ('Nnewi', 'Nnewi'), ('Calabar', 'Calabar')], max_length=120, null=True)),
                ('role', models.CharField(blank=True, choices=[('Fleet Managment', 'Fleet Managment'), ('Human Resources', 'Human Resources'), ('Procurement', 'Procurement'), ('Registrars', 'Registrars'), ('Stores', 'Stores'), ('RRBN Staff', 'RRBN Staff')], max_length=20)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('is_hod', models.BooleanField(default=True, help_text='Designates whether this user should be given HOD rights. ', verbose_name='HOD')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
