# Generated by Django 3.1 on 2020-11-01 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('vehicle_type', models.CharField(max_length=200)),
                ('engine_number', models.CharField(max_length=200)),
                ('chasis_number', models.CharField(max_length=200)),
                ('colour', models.CharField(max_length=200)),
                ('unit_assigned', models.CharField(max_length=200)),
                ('license_no', models.CharField(max_length=200)),
                ('insurance_details', models.CharField(max_length=200)),
                ('categories', models.ManyToManyField(blank=True, to='fleet.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.TextField(blank=True, null=True)),
                ('destination', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('departure_mileage', models.DecimalField(decimal_places=2, max_digits=50)),
                ('return_mileage', models.DecimalField(decimal_places=2, max_digits=50)),
                ('timeount', models.DateTimeField(auto_now_add=True)),
                ('timein', models.DateTimeField(auto_now_add=True)),
                ('authorised_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='deparment_hod', to=settings.AUTH_USER_MODEL)),
                ('driver_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hr.driver')),
                ('requisition_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='applying_staff', to=settings.AUTH_USER_MODEL)),
                ('vehicle_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fleet.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fault', models.CharField(max_length=200)),
                ('current_mileage', models.DecimalField(decimal_places=2, max_digits=50)),
                ('repair_details', models.CharField(max_length=200)),
                ('repair_cost', models.DecimalField(decimal_places=2, max_digits=50)),
                ('workshop_name', models.CharField(max_length=200)),
                ('mechanic_name', models.CharField(max_length=200)),
                ('repair_date', models.DateTimeField(auto_now_add=True)),
                ('driver_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hr.driver')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reported_by', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='verified_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_maintenance_date', models.DateTimeField(auto_now_add=True)),
                ('maintenance_due_date', models.DateTimeField(auto_now_add=True)),
                ('last_maintenance_mileage', models.DecimalField(decimal_places=2, max_digits=50)),
                ('current_mileage', models.DecimalField(decimal_places=2, max_digits=50)),
                ('workshop_name', models.CharField(max_length=200)),
                ('mechanic_name', models.CharField(max_length=200)),
                ('maintenance_cost', models.DecimalField(decimal_places=2, max_digits=50)),
                ('next_maintenance_date', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('driver_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hr.driver')),
                ('maintenance_approved_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fueling',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_mileage', models.DecimalField(decimal_places=2, max_digits=50)),
                ('fuel_input', models.IntegerField()),
                ('fuel_cost', models.DecimalField(decimal_places=2, max_digits=50)),
                ('station_name', models.CharField(max_length=200)),
                ('fueling_date', models.DateTimeField(auto_now_add=True)),
                ('authorised_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='protocol_hod', to=settings.AUTH_USER_MODEL)),
                ('driver_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hr.driver')),
                ('vehicle_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fleet.vehicle')),
            ],
        ),
    ]
