# Generated by Django 3.1 on 2020-11-19 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='re_order_credit',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=20),
            preserve_default=False,
        ),
    ]
