# Generated by Django 3.1 on 2020-12-12 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_auto_20201212_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='category',
            field=models.CharField(blank=True, choices=[('Pool Vehicle', 'Pool Vehicle'), ('Departmental Vehicle', 'Departmental Vehicle'), ('Zonal Office Vehicle', 'Zonal Office Vehicle')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='department_assigned',
            field=models.CharField(blank=True, choices=[('Monitoring', 'Monitoring'), ('Registrations', 'Registrations'), ('Institute', 'Institute'), ('Hr', 'HR'), ('Procurement', 'Procurement'), ('Finance', 'Finance'), ('Audit', 'Audit'), ('ICT', 'ICT'), ('Stores', 'Stores'), ('Protocol', 'PR & Protocol'), ('Registrars Office', 'Registrars Office'), ('Zonal Office ', 'Zonal Office')], max_length=120, null=True),
        ),
    ]
