# Generated by Django 3.1 on 2020-11-05 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fleet', '0002_auto_20201104_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='updated',
        ),
        migrations.AddField(
            model_name='category',
            name='entered_by',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='station',
            name='entered_by',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='entered_by',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.user'),
            preserve_default=False,
        ),
    ]
