# Generated by Django 3.1 on 2020-11-20 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_station_re_order_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='fueling',
            name='voucher_no',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
