# Generated by Django 3.1 on 2020-11-05 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_auto_20201105_0603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='unit_assigned',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='department_assigned',
            field=models.CharField(blank=True, choices=[('Monitoring', 'Monitoring'), ('Registrations', 'Registrations'), ('Hr', 'Hr'), ('Procurement', 'Procurement'), ('Finance', 'Finance'), ('Audit', 'Audit'), ('ICT', 'ICT'), ('Stores', 'Stores'), ('Protocol', 'Protocol')], max_length=120, null=True),
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='categories',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fleet.category'),
        ),
    ]
