# Generated by Django 3.1 on 2020-11-21 06:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import fleet.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fleet', '0003_fueling_voucher_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('refill_no', models.CharField(blank=True, default=fleet.models.increment_refill_no, max_length=500, null=True, unique=True)),
                ('station_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('station_credit', models.DecimalField(decimal_places=2, max_digits=20)),
                ('refill_credit_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('refill_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('refill_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='refill_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-refill_on'],
            },
        ),
    ]
