# Generated by Django 3.1 on 2020-11-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_refill'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
