# Generated by Django 3.1 on 2020-11-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_auto_20201105_0837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='categories',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='colour',
            field=models.CharField(blank=True, choices=[('White', 'White'), ('Grey', 'Grey'), ('Red', 'Red'), ('Blue', 'Blue'), ('Black', 'Black'), ('Brown', 'Brown'), ('Custom', 'Custom')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('Sedan', 'Sedan'), ('Bus', 'Bus'), ('Truck', 'Truck'), ('Van', 'Van'), ('Wagon', 'Wagon')], max_length=120, null=True),
        ),
    ]
