# Generated by Django 3.1 on 2020-12-24 18:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_auto_20201215_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='assign',
            name='projected_end_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='assign',
            name='projected_start_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='assign',
            name='approved_end_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='assign',
            name='approved_start_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
