# Generated by Django 3.1 on 2020-11-23 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0005_station_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='availability_status',
            field=models.IntegerField(default=1),
        ),
    ]
