# Generated by Django 3.1 on 2020-12-25 08:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0005_auto_20201224_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='approved_end_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='release',
            name='approved_start_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='release',
            name='actual_trip_end_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='release',
            name='actual_trip_start_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
