# Generated by Django 3.1 on 2020-11-06 21:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fleet', '0007_auto_20201106_0844'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assign',
            unique_together={('request_no', 'requesting_staff'), ('request_no', 'vehicle')},
        ),
    ]
