# Generated by Django 3.1 on 2020-12-31 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0007_auto_20201226_0912'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenance',
            options={'ordering': ['-maintenance_date']},
        ),
        migrations.RenameField(
            model_name='maintenance',
            old_name='current_maintenance_mileage',
            new_name='current_mileage',
        ),
        migrations.RenameField(
            model_name='maintenance',
            old_name='actual_maintenance_cost',
            new_name='maintenance_cost',
        ),
        migrations.RenameField(
            model_name='maintenance',
            old_name='actual_maintenance_date',
            new_name='maintenance_date',
        ),
        migrations.RenameField(
            model_name='maintenance',
            old_name='actual_maintenance_details',
            new_name='maintenance_details',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='next_maintenance_date',
        ),
        migrations.AddField(
            model_name='maintenance',
            name='target_maintenance_mileage',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=50),
            preserve_default=False,
        ),
    ]
