# Generated by Django 3.1 on 2020-11-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0008_auto_20201106_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='location',
            field=models.CharField(blank=True, choices=[('HQ', 'HQ'), ('Lagos', 'Lagos'), ('Asaba', 'Asaba'), ('Enugu', 'Enugu'), ('Port Harcourt', 'Port Harcourt'), ('Kano', 'Kano'), ('Sokoto', 'Sokoto'), ('Nnewi', 'Nnewi'), ('Calabar', 'Calabar')], max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='model',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='purchase_year',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='department_assigned',
            field=models.CharField(blank=True, choices=[('Monitoring', 'Monitoring'), ('Registrations', 'Registrations'), ('Hr', 'Hr'), ('Procurement', 'Procurement'), ('Finance', 'Finance'), ('Audit', 'Audit'), ('ICT', 'ICT'), ('Stores', 'Stores'), ('PR & Protocol', 'Protocol')], max_length=120, null=True),
        ),
    ]
