# Generated by Django 3.1 on 2020-11-07 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0009_auto_20201107_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='department_assigned',
            field=models.CharField(blank=True, choices=[('Monitoring', 'Monitoring'), ('Registrations', 'Registrations'), ('Hr', 'HR'), ('Procurement', 'Procurement'), ('Finance', 'Finance'), ('Audit', 'Audit'), ('ICT', 'ICT'), ('Stores', 'Stores'), ('Protocol', 'PR & Protocol')], max_length=120, null=True),
        ),
    ]
