# Generated by Django 3.1 on 2021-01-11 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0009_auto_20210111_2349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='release',
            options={'ordering': ['release_date']},
        ),
    ]
