# Generated by Django 3.1 on 2021-01-11 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0010_auto_20210111_2353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assign',
            options={'ordering': ['-request_no']},
        ),
    ]
