# Generated by Django 3.1 on 2020-11-07 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0011_auto_20201107_1050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assign',
            options={'ordering': ['-approved_date']},
        ),
    ]
