# Generated by Django 3.1 on 2021-01-25 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0012_auto_20210114_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='maintenance_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
