# Generated by Django 3.1 on 2020-11-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0012_auto_20201107_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='assign',
            name='trip_status',
            field=models.CharField(choices=[('created', 'Created'), ('completed', 'Completed')], default='created', max_length=120),
        ),
    ]
