# Generated by Django 3.1 on 2020-11-07 23:50

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fleet', '0014_auto_20201107_1936'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='release',
            options={'ordering': ['-release_date']},
        ),
        migrations.AddField(
            model_name='release',
            name='release_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterUniqueTogether(
            name='release',
            unique_together={('request_no', 'requesting_staff'), ('request_no', 'vehicle')},
        ),
    ]
