# Generated by Django 3.1 on 2020-11-09 00:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fleet', '0016_auto_20201109_0014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenance',
            old_name='remarks',
            new_name='maintenance_details',
        ),
        migrations.RemoveField(
            model_name='repair',
            name='verified_by',
        ),
        migrations.AddField(
            model_name='repair',
            name='recorded_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='protocol_officer', to='accounts.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='repair',
            name='fault',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='repair',
            name='reported_by',
            field=models.CharField(max_length=200),
        ),
    ]
