# Generated by Django 3.1 on 2020-11-09 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0017_auto_20201109_0049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repair',
            old_name='recorded_by',
            new_name='authorised_by',
        ),
    ]
