# Generated by Django 3.1 on 2020-11-09 09:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fleet', '0019_auto_20201109_0749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenance',
            old_name='maintenance_cost',
            new_name='actual_maintenance_cost',
        ),
        migrations.RenameField(
            model_name='maintenance',
            old_name='maintenance_details',
            new_name='actual_maintenance_details',
        ),
        migrations.RenameField(
            model_name='maintenance',
            old_name='current_mileage',
            new_name='current_maintenance_mileage',
        ),
        migrations.RenameField(
            model_name='maintenance',
            old_name='maintenance_approved_by',
            new_name='maintenance_scheduled_by',
        ),
        migrations.AddField(
            model_name='maintenance',
            name='actual_maintenance_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='maintenance_cost_estimate',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maintenance',
            name='maintenance_recorded_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='maintenance_recorded_by', to='accounts.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maintenance',
            name='projected_maintenance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='schduled_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='schedule_no',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='mechanic_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='maintenance_mechanic', to='fleet.workshop'),
        ),
    ]
