# Generated by Django 3.1 on 2020-11-09 09:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import fleet.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fleet', '0020_auto_20201109_0932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schedule_no', models.CharField(blank=True, default=fleet.models.increment_schedule_no, max_length=500, null=True)),
                ('driver', models.CharField(max_length=200)),
                ('last_maintenance_mileage', models.DecimalField(decimal_places=2, max_digits=50)),
                ('last_maintenance_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('maintenance_due_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('maintenance_cost_estimate', models.DecimalField(decimal_places=2, max_digits=50)),
                ('projected_maintenance', models.TextField(blank=True, null=True)),
                ('schduled_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('maintenance_scheduled_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='maintenance_scheduler', to=settings.AUTH_USER_MODEL)),
                ('mechanic_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='workshop_mechanic', to='fleet.workshop')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fleet.vehicle')),
                ('workshop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fleet.workshop')),
            ],
            options={
                'ordering': ['-schduled_on'],
                'unique_together': {('schedule_no', 'vehicle')},
            },
        ),
    ]
