# Generated by Django 3.1 on 2020-11-09 09:33

from django.db import migrations, models
import fleet.models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0021_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='schedule_no',
            field=models.CharField(blank=True, default=fleet.models.increment_schedule_no, max_length=500, null=True),
        ),
    ]
