# Generated by Django 3.1 on 2020-11-09 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0022_auto_20201109_0933'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['-scheduled_on']},
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='schduled_on',
            new_name='scheduled_on',
        ),
    ]
