from django.urls import path
from . import views
from .views import (
    DashboardTemplateView,
    LocationsListView,
    JobTitlesListView,
    JobTitleCreateView,
    JobTitleDetailView,
    JobTitleUpdateView,
    JobTitleDeleteView,
    PayGradeListView,
    PayGradeCreateView,
    PayGradeDetailView,
    PayGradeUpdateView,
    PayGradeDeleteView,
    StaffProfileListView,
    StaffProfileDetailView,
    LeaveRequestListView,
    LeaveRequestDetailView,
    AssignLeaveRequest,
    LeaveApprovalListView,
    LeaveAssignmentListView,
    LeaveApprovalDetailView,
    LeaveAssignmentDetailView,
    EndLeave,
    LeaveHistoryListView,
    LeaveHistoryDetailView,
    CourseListView,
    CourseCreateView,
    CourseDetailView,
    CourseUpdateView,
    CourseDeleteView,
    TrainingListView,
    TrainingCreateView,
    TrainingDetailView,
    TrainingUpdateView,
    TrainingDeleteView,
    CategoryListView,
    CategoryCreateView,
    CategoryDetailView,
    CategoryUpdateView,
    CategoryDeleteView,
    VendorListView,
    VendorCreateView,
    VendorDetailView,
    VendorUpdateView,
    VendorDeleteView,
    AppraisalCreateView,
    AppraisalListView,
    AppraisalDetailView,
    AppraisalUpdateView,
    AppraisalDeleteView,
    ScheduleCreateView,
    ScheduleListView,
    ScheduleDetailView,
    ScheduleUpdateView,
    ScheduleDeleteView,
    PerformanceCreateView,
    PerformanceListView,
    PerformanceDetailView,
    PerformanceUpdateView,
    PerformanceDeleteView,
    DisciplineCreateView,
    DisciplineListView,
    DisciplineDetailView,
    DisciplineUpdateView,
    DisciplineDeleteView,
    ComplianceCreateView,
    ComplianceListView,
    ComplianceDetailView,
    ComplianceUpdateView,
    ComplianceDeleteView,

   
)


app_name = 'hr'

urlpatterns = [
	path('dashboard/', DashboardTemplateView.as_view(), name='hr_dashboard'),
    path('locations_list/', LocationsListView.as_view(), name='locations_list'),
    path('job_titles_list/', JobTitlesListView.as_view(), name='job_titles_list'),
    path('add_job_title/', JobTitleCreateView.as_view(), name='add_job_title'),
    path('<uuid:pk>/job_title_detail/', JobTitleDetailView.as_view(), name='job_title_detail'),
    path('<uuid:pk>/job_title_update/', JobTitleUpdateView.as_view(), name='job_title_update'),
    path('<uuid:id>/job_title_delete/', JobTitleDeleteView.as_view(), name='job_title_delete'),
    path('pay_grade_list/', PayGradeListView.as_view(), name='pay_grade_list'),
    path('add_pay_grade/', PayGradeCreateView.as_view(), name='add_pay_grade'),
    path('<uuid:pk>/pay_grade_detail/', PayGradeDetailView.as_view(), name='pay_grade_detail'),
    path('<uuid:pk>/pay_grade_update/', PayGradeUpdateView.as_view(), name='pay_grade_update'),
    path('<uuid:id>/pay_grade_delete/', PayGradeDeleteView.as_view(), name='pay_grade_delete'),
    path('staff_profile_list/', StaffProfileListView.as_view(), name='staff_profile_list'),
    path('<uuid:pk>/staff_profile_detail/', StaffProfileDetailView.as_view(), name='staff_profile_detail'),
    path('leave_request_list/', LeaveRequestListView.as_view(), name='leave_request_list'),
    path('approval_list/', LeaveApprovalListView.as_view(), name='leave_approval_list'),
    path('assignment_list/', LeaveAssignmentListView.as_view(), name='leave_assignment_list'),
    path('<uuid:pk>/leave_request_detail/', LeaveRequestDetailView.as_view(), name='leave_request_detail'),
    path('<uuid:id>/leave_request_details/', views.leave_request_details, name='leave_request_details'),
    path('<uuid:id>/leave_request_approved/', views.approve_leave_request, name='approve_leave_request'),
    path('<uuid:id>/leave_request_rejected/', views.reject_leave_request, name='reject_leave_request'),
    path('<uuid:id>/assign_leave_request', AssignLeaveRequest.as_view(), name='assign_leave_request'),
    path('<uuid:pk>/leave_approval_detail/', LeaveApprovalDetailView.as_view(), name='leave_approval_detail'),
    path('<uuid:pk>/leave_assignment_detail/', LeaveAssignmentDetailView.as_view(), name='leave_assignment_detail'),
    path('<uuid:id>/end_leave', EndLeave.as_view(), name='end_leave'),
    path('leave_history_list/', LeaveHistoryListView.as_view(), name='leave_history_list'),
    path('<uuid:pk>/leave_history_detail/', LeaveHistoryDetailView.as_view(), name='leave_history_detail'),
    path('add_category/', CategoryCreateView.as_view(), name='add_category'),
    path('category_list/', CategoryListView.as_view(), name='category_list'), 
    path('<uuid:pk>/category_detail/', CategoryDetailView.as_view(), name='category_detail'),
    path('<uuid:pk>/category_update/', CategoryUpdateView.as_view(), name='category_update'),
    path('<uuid:id>/category_delete/', CategoryDeleteView.as_view(), name='category_delete'),
    path('add_vendor/', VendorCreateView.as_view(), name='add_vendor'),
    path('vendor_list/', VendorListView.as_view(), name='vendor_list'),
    path('<uuid:pk>/vendor_detail/', VendorDetailView.as_view(), name='vendor_detail'),
    path('<uuid:pk>/vendor_update/', VendorUpdateView.as_view(), name='vendor_update'),
    path('<uuid:id>/vendor_delete/', VendorDeleteView.as_view(), name='vendor_delete'),
    path('add_course/', CourseCreateView.as_view(), name='add_course'),
    path('course_list/', CourseListView.as_view(), name='course_list'),
    path('<uuid:pk>/course_detail/', CourseDetailView.as_view(), name='course_detail'),
    path('<uuid:pk>/course_update/', CourseUpdateView.as_view(), name='course_update'),
    path('<uuid:id>/course_delete/', CourseDeleteView.as_view(), name='course_delete'),
    path('<uuid:id>/add_training', TrainingCreateView.as_view(), name='add_training'),
    path('training_list/', TrainingListView.as_view(), name='training_list'),
    path('<uuid:pk>/training_detail/', TrainingDetailView.as_view(), name='training_detail'),
    path('<uuid:pk>/training_update/', TrainingUpdateView.as_view(), name='training_update'),
    path('<uuid:id>/training_delete/', TrainingDeleteView.as_view(), name='training_delete'),
    path('add_appraisal/', AppraisalCreateView.as_view(), name='add_appraisal'),
    path('appraisal_list/', AppraisalListView.as_view(), name='appraisal_list'), 
    path('<uuid:pk>/appraisal_detail/', AppraisalDetailView.as_view(), name='appraisal_detail'),
    path('<uuid:pk>/appraisal_update/', AppraisalUpdateView.as_view(), name='appraisal_update'),
    path('<uuid:id>/appraisal_delete/', AppraisalDeleteView.as_view(), name='appraisal_delete'),
    path('add_schedule/', ScheduleCreateView.as_view(), name='add_schedule'),
    path('schedule_list/', ScheduleListView.as_view(), name='schedule_list'), 
    path('<uuid:pk>/schedule_detail/', ScheduleDetailView.as_view(), name='schedule_detail'),
    path('<uuid:pk>/schedule_update/', ScheduleUpdateView.as_view(), name='schedule_update'),
    path('<uuid:id>/schedule_delete/', ScheduleDeleteView.as_view(), name='schedule_delete'),
    path('<uuid:id>/add_performance', PerformanceCreateView.as_view(), name='add_performance'),
    path('performance_list/', PerformanceListView.as_view(), name='performance_list'), 
    path('<uuid:pk>/performance_detail/', PerformanceDetailView.as_view(), name='performance_detail'),
    path('<uuid:pk>/performance_update/', PerformanceUpdateView.as_view(), name='performance_update'),
    path('<uuid:id>/performance_delete/', PerformanceDeleteView.as_view(), name='performance_delete'),
    path('add_discipline/', DisciplineCreateView.as_view(), name='add_discipline'),
    path('discipline_list/', DisciplineListView.as_view(), name='discipline_list'), 
    path('<uuid:pk>/discipline_detail/', DisciplineDetailView.as_view(), name='discipline_detail'),
    path('<uuid:pk>/discipline_update/', DisciplineUpdateView.as_view(), name='discipline_update'),
    path('<uuid:id>/discipline_delete/', DisciplineDeleteView.as_view(), name='discipline_delete'),
    path('<uuid:id>/add_compliance', ComplianceCreateView.as_view(), name='add_compliance'),
    path('compliance_list/', ComplianceListView.as_view(), name='compliance_list'), 
    path('<uuid:pk>/compliance_detail/', ComplianceDetailView.as_view(), name='compliance_detail'),
    path('<uuid:pk>/compliance_update/', ComplianceUpdateView.as_view(), name='compliance_update'),
    path('<uuid:id>/compliance_delete/', ComplianceDeleteView.as_view(), name='compliance_delete'),
    
    
    
    
	
    
    ]