# Generated by Django 3.1 on 2020-11-11 10:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Procurement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=200)),
                ('project_tasks', models.CharField(max_length=200)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=50)),
                ('project_total', models.DecimalField(decimal_places=2, max_digits=50)),
                ('task_start_date', models.DateTimeField(auto_now_add=True)),
                ('task_end_date', models.DateTimeField(auto_now_add=True)),
                ('completion_status', models.CharField(max_length=200)),
                ('task_dependencies', models.CharField(max_length=200)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
