# Generated by Django 3.1 on 2024-02-08 12:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import procurement.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField()),
                ('added_on', models.DateField(default=datetime.date.today)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='project_category_added_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('description', models.TextField()),
                ('date_created', models.DateField(default=datetime.date.today)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='project_vendor_added_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_no', models.CharField(max_length=200)),
                ('contract_name', models.CharField(max_length=200)),
                ('contract_description', models.TextField()),
                ('contact_award_date', models.DateField(default=datetime.date.today)),
                ('contact_award_amount', models.DecimalField(decimal_places=2, max_digits=50)),
                ('projected_start_date', models.DateField(default=datetime.date.today)),
                ('projected_end_date', models.DateField(default=datetime.date.today)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('contract_status', models.CharField(blank=True, choices=[('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Abandoned', 'Abandoned')], max_length=120, null=True)),
                ('performance_rating', models.IntegerField()),
                ('remarks', models.TextField()),
                ('date_documented', models.DateField(default=datetime.date.today)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='procurement.category')),
                ('documented_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='project_documented_by', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='procurement.vendor')),
            ],
            options={
                'ordering': ['-date_documented'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_no', models.CharField(blank=True, default=procurement.models.increment_contract_no, max_length=500, null=True, unique=True)),
                ('contract_name', models.CharField(max_length=200)),
                ('contract_description', models.TextField()),
                ('contact_award_date', models.DateField(default=datetime.date.today)),
                ('contact_award_amount', models.DecimalField(decimal_places=2, max_digits=50)),
                ('projected_start_date', models.DateField(default=datetime.date.today)),
                ('projected_end_date', models.DateField(default=datetime.date.today)),
                ('contract_status', models.CharField(default='Awarded', max_length=200)),
                ('contract_award_letter', models.FileField(blank=True, upload_to='%Y/%m/%d/')),
                ('vendor_proposal', models.FileField(blank=True, upload_to='%Y/%m/%d/')),
                ('date_added', models.DateField(default=datetime.date.today)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='contract_added_by', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='procurement.category')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='procurement.vendor')),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
    ]
